// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SessionUIClient is the client API for SessionUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionUIClient interface {
	// ListEngineSpecs returns a list of Session Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SessionUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type sessionUIClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionUIClient(cc grpc.ClientConnInterface) SessionUIClient {
	return &sessionUIClient{cc}
}

func (c *sessionUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SessionUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SessionUI_ServiceDesc.Streams[0], "/v1.SessionUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SessionUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type sessionUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *sessionUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sessionUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.SessionUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionUIServer is the server API for SessionUI service.
// All implementations must embed UnimplementedSessionUIServer
// for forward compatibility
type SessionUIServer interface {
	// ListEngineSpecs returns a list of Session Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, SessionUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedSessionUIServer()
}

// UnimplementedSessionUIServer must be embedded to have forward compatible implementations.
type UnimplementedSessionUIServer struct {
}

func (UnimplementedSessionUIServer) ListEngineSpecs(*ListEngineSpecsRequest, SessionUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedSessionUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedSessionUIServer) mustEmbedUnimplementedSessionUIServer() {}

// UnsafeSessionUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionUIServer will
// result in compilation errors.
type UnsafeSessionUIServer interface {
	mustEmbedUnimplementedSessionUIServer()
}

func RegisterSessionUIServer(s grpc.ServiceRegistrar, srv SessionUIServer) {
	s.RegisterService(&SessionUI_ServiceDesc, srv)
}

func _SessionUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionUIServer).ListEngineSpecs(m, &sessionUIListEngineSpecsServer{stream})
}

type SessionUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type sessionUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *sessionUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SessionUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SessionUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionUI_ServiceDesc is the grpc.ServiceDesc for SessionUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SessionUI",
	HandlerType: (*SessionUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _SessionUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _SessionUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "session-ui.proto",
}
